// Nivel 9 — generado por el editor de grilla
window.LEVELS[11] = [
  "es muy lindo",
  "poder editarlo",
  "                                               (*)",
  "",
  "                                  crear cajitas ",
  "                                 por donde saltar",
  "            ________",
  "",
  "   _______            ______",
  "                        _______",
  "                            ______",
  "",
  "",
  "                                 ___________ ",
  "",
  "                                            ______",
  "y si bajo mucho                        ___",
  "                                         ___",
  "                                           ___",
  "                   tengo                     ___",
  "                       que                     ___",
  "                           volver             ___",
  "                                   a       ___",
  "                                     subir",
];
