// Nivel escrito con el modo edición de Casus Liber
window.LEVELS[2] = [
  "",
  "",
  "",
  "                          D",
  "                          E",
  "",
  "                          J",
  "",
  "                         A",
  "",
  "                          R",
  "",
  "                           T",
  "",
  "                            E",
  "",
  "",
  "",
  "",
  "                               C",
  "",
  "                                A",
  "",
  "                                E",
  "                                E",
  "                                 E",
  "                                  E",
  "                                  E",
  "                                    E",
  "                                   E",
  "                                  E",
  "                                 E",
  "                                R",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "(*)",
];
