// Nivel generado con el Creador de niveles de Casus Liber
window.LEVELS[12] = [
  "a                                             m",
  " b                                           n",
  "  c                                         o",
  "   d                                       p",
  "    e                                     q",
  "                                         r     (*)",
  "                                        s",
  "       f                               t",
  "        g                             u",
  "                                     v",
  "          h                         w",
  "           i                       x",
  "            j                     y",
  "                                 z",
  "",
  "               k",
  "                l             z",
  "                 m           y",
  "                  n         x",
  "                   o       w",
  "                    p     v",
  "                     q   u",
  "                      r t",
  "                       s",
];
