// Nivel escrito con el modo edición de Casus Liber
window.LEVELS[6] = [
  "                                —Bartleby —dije en tono aún más suave—, venga, ",
  "",
  "",
  "",
  "no le voy a pedir que haga nada ",
  "que usted preferiría no hacer. ",
  "",
  "",
  "",
  "",
  "                                Sólo quiero conversar con usted.",
  "",
  "                                            ",
  "                           ",
  "",
  "",
  "",
  "",
  "",
  "Con esto, se me acercó ",
  "                            ",
  "                        silenciosamente.",
  "",
  "",
  "",
  "                                                 ",
  "                                                               #############       (*)",
  "                                                                 #########",
  "",
  "",
  "",
  "",
  "                                —¿Quiere decirme, Bartleby, dónde ha nacido?",
  "",
  "  —Preferiría no hacerlo.",
  "",
  "",
  "                                —¿Quiere contarme algo de usted?",
  "",
  "  —Preferiría no hacerlo.    ",
];
window.LEVEL_TITLES[6] = "Bartleby el escribiente";
